Repository protocolguild/documentation, pull requests merged in 2024-04, with the labels that each got.

#152 remove domothy
  docs/9-membership.md
Labels: remove member

#156 Update team
  docs/09-membership.md
Labels: change affiliation

#157 Update Preston Van Loon weight to 1
  docs/09-membership.md
Labels: change weight
