Repository protocolguild/documentation, pull requests merged in 2024-01, with the labels that each got.

#125 Update dapplion team
  README.md
Labels: change affiliation

#129 Remove Ben Edgington
  README.md
Labels: remove member

#127 Add NC to Lodestar
  README.md
Labels: add member

#128 add Josh Rudolf
  README.md
Labels: add member

#132 Change Mikhail’s weight to 1.0
  README.md
Labels: change weight

#131 Add Mary Maller from EF Cryptography
  README.md
Labels: add member
