Repository protocolguild/documentation, pull requests merged in 2024-02, with the labels that each got.

#137 Remove Afri Schoedon
  README.md
Labels: remove member

#135 Add Reth
  docs/4-roles-expectations.md
Labels: add team

#143 Add joshie
  docs/9-membership.md
Labels: add member
