Repository protocolguild/documentation, pull requests merged in 2025-02, with the labels that each got.

#299 Add Nimbus execution client
  docs/01-eligibility.md
Labels: add team

#321 Move Jacek Glen to full-time
  docs/02-membership.md
Labels: change weight, processed

#323 Update (reth) contributions and weight
  docs/02-membership.md
Labels: change weight, processed

#326 Remove hwwhww
  docs/02-membership.md
Labels: remove member, processed
